-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2021-06-07 18:56:24 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE mx3.erm_im_main_agg_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.fric_cash_flows_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.intra_trade_val_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.job_audit_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_cash_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_ci_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_counterpart_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_deltahedge_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_fr_vol_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_greeks_topo_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_intravar_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_legal_agr_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_mktp_smile_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_mktp_vol_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_pl_d_rep_bo_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_pl_d_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_pl_d_rep_fo_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_pl_var_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_portfolio_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_refspot_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_rho_topo_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_si_static_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_smc_intraday_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_tarf_data_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_tarf_data_rep_intraday_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_tarf_fixings_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_tarf_fixings_rep_iday_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_topo_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_trade_audit_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_trade_cs_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_trade_fix_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_trade_intr_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_trade_pay_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_trade_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_trade_rep_intraday_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_trade_si_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_trade_ts_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_trade_value_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_user_group_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_var_mktop_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_var_v1_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_vol_intraday_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.mxt_zc_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.tremor1_basket_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.tremor1_outputs_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.trn_entd_dbf_rep_ext CASCADE CONSTRAINTS;

DROP TABLE mx3.usr_info_dbf_rep_ext CASCADE CONSTRAINTS;